-- 1. Main Staff Loan Application Table
CREATE TABLE staff_loan_application (
    application_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_no       VARCHAR(30) NOT NULL UNIQUE, -- e.g. SLA-20260708-0001

    staff_id             VARCHAR(20) NOT NULL,
    staff_name           VARCHAR(150) NOT NULL,
    position_title       VARCHAR(100) NOT NULL,
    department_name      VARCHAR(150) NOT NULL,

    nrc_no               VARCHAR(50) NOT NULL,
    father_name          VARCHAR(150) NOT NULL,
    father_nrc_no        VARCHAR(50) NULL,
    permanent_address    TEXT NOT NULL,
    phone_no             VARCHAR(30) NOT NULL,

    gross_salary         NUMERIC(18,2) NOT NULL,
    loan_type            VARCHAR(50) NOT NULL DEFAULT 'Staff Loan',
    loan_amount          NUMERIC(18,2) NOT NULL,
    salary_multiple      INT NOT NULL,
    cb_account_no        VARCHAR(30) NOT NULL,
    
    guarantor1_name      VARCHAR(150) NULL,
    guarantor1_email     VARCHAR(150) NULL,
    guarantor2_name      VARCHAR(150) NULL,
    guarantor2_email     VARCHAR(150) NULL,
    
    hod_name             VARCHAR(150) NULL,
    hod_email            VARCHAR(150) NULL,

    applicant_agreement  BOOLEAN NOT NULL DEFAULT FALSE,
    declaration_1        BOOLEAN NOT NULL DEFAULT FALSE,
    declaration_2        BOOLEAN NOT NULL DEFAULT FALSE,
    declaration_3        BOOLEAN NOT NULL DEFAULT FALSE,
    declaration_4        BOOLEAN NOT NULL DEFAULT FALSE,

    overall_status       VARCHAR(30) NOT NULL DEFAULT 'PENDING', 
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by           VARCHAR(100) NULL,
    updated_at           TIMESTAMPTZ NULL,
    updated_by           VARCHAR(100) NULL
);

-- 2. Guarantors Table (Handles both G1 and G2 using guarantor_seq)
CREATE TABLE staff_loan_guarantor (
    guarantor_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id       BIGINT NOT NULL,
    guarantor_seq        SMALLINT NOT NULL,   -- 1 = Guarantor 1, 2 = Guarantor 2

    guarantor_staff_id   VARCHAR(20) NOT NULL,
    guarantor_name       VARCHAR(150) NOT NULL,
    guarantor_email      VARCHAR(150) NOT NULL,
    position_title       VARCHAR(100) NOT NULL,
    nrc_no               VARCHAR(50) NOT NULL,
    father_name          VARCHAR(150) NOT NULL,
    department_name      VARCHAR(150) NOT NULL,
    permanent_address    TEXT NOT NULL,

    declaration_agreed   BOOLEAN NOT NULL DEFAULT FALSE,
    approval_status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_at          TIMESTAMPTZ NULL,
    remarks              TEXT NULL,

    mail_sent_flag       BOOLEAN NOT NULL DEFAULT FALSE,
    mail_sent_at         TIMESTAMPTZ NULL,

    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NULL,

    CONSTRAINT fk_staff_loan_guarantor_app
        FOREIGN KEY (application_id) REFERENCES staff_loan_application(application_id) ON DELETE CASCADE,

    CONSTRAINT uq_staff_loan_guarantor_app_seq
        UNIQUE (application_id, guarantor_seq),

    CONSTRAINT ck_staff_loan_guarantor_seq
        CHECK (guarantor_seq IN (1,2)),

    CONSTRAINT ck_staff_loan_guarantor_status
        CHECK (approval_status IN ('PENDING','APPROVED','REJECTED'))
);

-- 3. HOD Approval Table
CREATE TABLE staff_loan_hod_approval (
    hod_approval_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id       BIGINT NOT NULL,

    hod_name             VARCHAR(150) NOT NULL,
    hod_position         VARCHAR(100) NOT NULL,
    hod_department       VARCHAR(150) NOT NULL,
    hod_email            VARCHAR(150) NULL,

    remarks              TEXT NULL,
    declaration_agreed   BOOLEAN NOT NULL DEFAULT FALSE,
    approval_status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_at          TIMESTAMPTZ NULL,

    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NULL,

    CONSTRAINT fk_staff_loan_hod_app
        FOREIGN KEY (application_id) REFERENCES staff_loan_application(application_id) ON DELETE CASCADE,

    CONSTRAINT uq_staff_loan_hod_app
        UNIQUE (application_id),

    CONSTRAINT ck_staff_loan_hod_status
        CHECK (approval_status IN ('PENDING','APPROVED','REJECTED'))
);

-- 4. HR Approval Table
CREATE TABLE staff_loan_hr_approval (
    hr_approval_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id       BIGINT NOT NULL,

    hr_name              VARCHAR(150) NOT NULL,
    hr_department        VARCHAR(150) NOT NULL,
    hr_remarks           TEXT NULL,
    declaration_agreed   BOOLEAN NOT NULL DEFAULT FALSE,
    approval_status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_at          TIMESTAMPTZ NULL,

    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NULL,

    CONSTRAINT fk_staff_loan_hr_app
        FOREIGN KEY (application_id) REFERENCES staff_loan_application(application_id) ON DELETE CASCADE,
    CONSTRAINT uq_staff_loan_hr_app
        UNIQUE (application_id),
    CONSTRAINT ck_staff_loan_hr_status
        CHECK (approval_status IN ('PENDING','APPROVED','REJECTED'))
);

-- 5. Risk Management Table
CREATE TABLE staff_loan_risk_approval (
    risk_approval_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id       BIGINT NOT NULL,

    staff_loan_record    VARCHAR(100) NOT NULL,
    gm_name              VARCHAR(150) NOT NULL,
    loan_record_no       VARCHAR(100) NOT NULL,
    loan_id              VARCHAR(100) NOT NULL,
    loan_ld_no           VARCHAR(100) NOT NULL,
    approved_amount      NUMERIC(18,2) NOT NULL,
    risk_remark          TEXT NULL,
    approval_status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_at          TIMESTAMPTZ NULL,

    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NULL,

    CONSTRAINT fk_staff_loan_risk_app
        FOREIGN KEY (application_id) REFERENCES staff_loan_application(application_id) ON DELETE CASCADE,
    CONSTRAINT uq_staff_loan_risk_app
        UNIQUE (application_id),
    CONSTRAINT ck_staff_loan_risk_status
        CHECK (approval_status IN ('PENDING','APPROVED','REJECTED'))
);

-- 6. Mail Log Table
CREATE TABLE staff_loan_mail_log (
    mail_log_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id       BIGINT NOT NULL,
    guarantor_id         BIGINT NULL,
    recipient_email      VARCHAR(150) NOT NULL,
    mail_type            VARCHAR(50) NOT NULL,
    mail_subject         VARCHAR(300) NOT NULL,
    sent_status          VARCHAR(20) NOT NULL DEFAULT 'SENT',
    sent_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    error_message        TEXT NULL,

    CONSTRAINT fk_staff_loan_mail_log_app
        FOREIGN KEY (application_id) REFERENCES staff_loan_application(application_id) ON DELETE CASCADE,

    CONSTRAINT fk_staff_loan_mail_log_guarantor
        FOREIGN KEY (guarantor_id) REFERENCES staff_loan_guarantor(guarantor_id) ON DELETE SET NULL
);